### ISSUE TITLE
cat-select: label is truncated when selecting multiple entities

### ISSUE THREAD

**Issue by heyhoho** [haiilo/catalyst#145] opened 2023-02-09 14:41 UTC
when using cat-select with multiple attribute.

Ref: https://haiilo.atlassian.net/browse/TSP-242

When user tries to select multiple entities in cat-select component, the label is truncated.

**Comment by emmoldovan** [comment] 2023-02-17 15:16
It was fixed with the font-family change to Lato. The issue is reproducible only with Source Sans Pro font family


![Image](https://user-images.githubusercontent.com/89849556/219693258-e94e89dd-d4b4-439b-ba4b-4e7d2818488d.png)

**Closed** 2023-06-15 09:58 UTC
Labels: bug
