### ISSUE TITLE
Date picker accessibility: Choose/Change date and closing dialog via keyboard

### ISSUE THREAD

**Issue by denise-hertwig** [haiilo/catalyst#437] opened 2023-12-14 14:00 UTC
As a user, I want to use the datepicker via keyboard. 

- Choosing a date with keyboard should be possible
- Choosing a date range with keyboard should be possible
- Change date with keyboard should be possible
- Close datepicker with keyboard should be possible

**Comment by denise-hertwig** [comment] 2023-12-14 14:01
Jira Ticket:https://haiilo.atlassian.net/browse/COYOFOUR-21893

**Comment by glushkova91** [comment] 2024-03-04 12:57
Duplicate of #310. After short investigation I can say that flatpickr library doesn't allow keyboard navigation if `allowInput` config is on(and in catalyst this flag is always true).

**Closed** 2024-05-29 21:09 UTC
